### ISSUE TITLE
Not working on Windows 8 - Tested on Docker container

### ISSUE THREAD

**Issue by devrj8** [xdsswar/nfx-lib#2]
Hi @xdsswar, love your work 👍  in this repo. I was working on app, I thought of using your lib and started testing on compatibility on various windows versions. Started testing on Windows 8(in a Docker container).

On **Windows 11** it is working great 👍 
![image](https://github.com/user-attachments/assets/eed2b7a4-61d8-4de7-97ca-6473fd354375)

### Issue Replication:
On **Windows 8** it is not working at all. 
Screenshot : 
![image](https://github.com/user-attachments/assets/3e9ab86d-1332-450f-a3e4-3405a462ed3b)

**Console error :** 
<img width="668" alt="image" src="https://github.com/user-attachments/assets/7e19421f-d543-4e78-beed-68fea655af22">

Could you please take a look at the issue. 

### Testing steps : 
I see you comment on other issue, yes it is hard to install and test on different version of windows. I have used docker container to test it. 

1. Install Docker desktop : https://www.docker.com/products/docker-desktop/
2. Docker compose file location : https://github.com/dockur/windows
3. I have used below docker compose file, Just replace "C:\Users\your-location"  with your host location path(with JavaFX app).
4. Open power shell change directory to compose.yml file. run  > `docker compose up`
5. Container is up, go to http://localhost:8006/ - you will see the windows here
6. Complete the windows installation
7. On file explorer > Network > host.lan > Data > here it will show "Host file path" which is configured in compose file.

### Docker compose.yml
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win8"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - C:\Users\your-location:/shared
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

```
